async function main() {
  const { main: runAfkLeaveTests } = require('./afk-leave.test');
  const { main: runAfkLeaveUiTests } = require('./afk-leave-ui.test');
  const { main: runOnlineMembersTests } = require('./online-members.test');
  const { main: runAiTests } = require('./ai.test');
  const { main: runAutomodTests } = require('./automod.test');
  const { main: runApplicationsTests } = require('./applications.test');
  const { main: runBrandRefreshTests } = require('./brand-refresh.test');
  const { main: runCommandsTests } = require('./commands.test');
  const { main: runAnnouncementCommandRuntimeTests } = require('./command-runtime-announcements.test');
  const { main: runLawCommandRuntimeTests } = require('./command-runtime-law.test');
  const { main: runClientReadyRuntimeTests } = require('./client-ready-runtime.test');
  const { main: runCopyRuntimeTests } = require('./copy-runtime.test');
  const { main: runDatabaseTests } = require('./database.test');
  const { main: runDeepSeekTests } = require('./deepseek.test');
  const { main: runConfigTests } = require('./config.test');
  const { main: runEmbedsTests } = require('./embeds.test');
  const { main: runGuildRuntimeTests } = require('./guild-runtime.test');
  const { main: runLeakGuardTests } = require('./leak-guard.test');
  const { main: runLawTests } = require('./law.test');
  const { main: runMediaShareTests } = require('./media-share.test');
  const { main: runMediaShareUiTests } = require('./media-share-ui.test');
  const { main: runMojibakeTests } = require('./mojibake.test');
  const { main: runReleaseNotesTests } = require('./release-notes.test');
  const { main: runReportRequestsTests } = require('./report-requests.test');
  const { main: runReportRequestsUiTests } = require('./report-requests-ui.test');
  const { main: runRanksTests } = require('./ranks.test');
  const { main: runRuntimeAccessHelpersTests } = require('./runtime-access-helpers.test');
  const { main: runRuntimeAutomationHelpersTests } = require('./runtime-automation-helpers.test');
  const { main: runRuntimeCommandHelpersTests } = require('./runtime-command-helpers.test');
  const { main: runRuntimeFamilyHelpersTests } = require('./runtime-family-helpers.test');
  const { main: runRuntimeLifecycleHelpersTests } = require('./runtime-lifecycle-helpers.test');
  const { main: runRuntimeNotificationHelpersTests } = require('./runtime-notification-helpers.test');
  const { main: runSecurityTests } = require('./security.test');
  const { main: runStorageTests } = require('./storage.test');
  const { main: runSupportTicketTests } = require('./support-tickets.test');
  const { main: runSupportTicketUiTests } = require('./support-ticket-ui.test');
  const { main: runTelegramTests } = require('./telegram.test');
  const { main: runTelegramHandlersTests } = require('./telegram-handlers.test');
  const { main: runTicketBridgeTests } = require('./ticket-bridge.test');
  const { main: runAnnouncementsTests } = require('./announcements.test');
  const { main: runTsDebtTests } = require('./ts-debt.test');
  const { main: runTsMigrationTests } = require('./ts-migration.test');

  await runAfkLeaveTests();
  await runAfkLeaveUiTests();
  await runOnlineMembersTests();
  await runAiTests();
  await runAutomodTests();
  await runApplicationsTests();
  await runBrandRefreshTests();
  await runCommandsTests();
  await runAnnouncementCommandRuntimeTests();
  await runLawCommandRuntimeTests();
  await runClientReadyRuntimeTests();
  await runCopyRuntimeTests();
  await runDatabaseTests();
  await runDeepSeekTests();
  await runConfigTests();
  await runEmbedsTests();
  await runGuildRuntimeTests();
  await runLeakGuardTests();
  await runLawTests();
  await runMediaShareTests();
  await runMediaShareUiTests();
  await runMojibakeTests();
  await runReleaseNotesTests();
  await runReportRequestsTests();
  await runReportRequestsUiTests();
  await runRanksTests();
  await runRuntimeAccessHelpersTests();
  await runRuntimeAutomationHelpersTests();
  await runRuntimeCommandHelpersTests();
  await runRuntimeFamilyHelpersTests();
  await runRuntimeLifecycleHelpersTests();
  await runRuntimeNotificationHelpersTests();
  await runSecurityTests();
  await runStorageTests();
  await runSupportTicketTests();
  await runSupportTicketUiTests();
  await runTelegramTests();
  await runTelegramHandlersTests();
  await runTicketBridgeTests();
  await runAnnouncementsTests();
  await runTsDebtTests();
  await runTsMigrationTests();
  console.log('ALL TEST SUITES PASSED');
}

if (require.main === module) {
  main().catch(error => {
    console.error(error);
    process.exit(1);
  });
}

module.exports = { main };
